### ISSUE TITLE
Form UI Elements

### ISSUE THREAD

**Issue by tandav** [tandav/ultrasonic-stethoscope#10]
# TODO
- [ ] make checkbox - show original values / show values from moving average
- [ ] moving_average_window_size - (add ability to input from Form)
- [ ] draw accuracy  (add ability to input from Form) (how many points from buffer should be drawn)
- [ ] buffer size
- [ ] x-axis zoom
