### ISSUE TITLE
Maybe TODO

### ISSUE THREAD

**Issue by tandav** [tandav/ultrasonic-stethoscope#19]
- Make Rudshel ADC data visualisation boilerplate as separate repo?

# UX improvements
- [x] Create a loop with timeout that tries to connect to arduino. (to prevent `could not open serial port` error)
- [x] Fix thread issue, which forces you to reboot arduino after each run of the app.
- [x] Print length of recorded signal in seconds
- [ ] change rudshel project name
